#!/usr/bin/env bash

# fail on error
set -eo pipefail

# trace
set -x

if [ $# -ne 1 ] ; then
    echo ${*}
    echo "Usage ${0} install_name" 1>&2
    exit
fi

# from the windows python installer
declare -r install_name="${1}"

# get and validate the python root
declare -r PR="${PYENV_ROOT}/versions/${install_name}"
if [ ! -d "${PR}" ] ; then
    echo "${PR} must exist"
    exit
fi

function patch_python {

    # get exes/dlls into Scripts
    declare -r scripts_dir="${PR}/Scripts"
    echo "ln -rs ${PR}/*.exe ${PR}/*.dll ${scripts_dir}"
    ln -rs ${PR}/*.exe ${PR}/*.dll "${scripts_dir}" 2>/dev/null || true

    # link Scripts to bin
    declare -r bin_dir="${PR}/bin"
    rm -rf "${bin_dir}" || true
    echo "ln -rs ${scripts_dir} ${bin_dir}"
    ln -rs "${scripts_dir}" "${bin_dir}"

    # check
    echo "ls ${bin_dir}"
    ls "${bin_dir}"
}

function link_i {
    declare -r targ="${ASV%/}/t/pyenv"
    printf "\nBUILD: link to ${targ}\n"
    ln -rfs "${PYENV_ROOT}/versions/${install_name}" "${targ}"
}

patch_python

link_i
