#!/usr/bin/env bash

# fail on error
set -eo pipefail

function do_git {
    cd "${1}"
    echo 1>&2
    echo "$(pwd)" 1>&2
    git -C "${1}" checkout upstream || true
    git pull || true
    git -C "${1}" checkout master
    git pull
}

if [ x"$(expr substr $(uname -s) 1 5)" = x'Linux' ]; then
    declare -ar dirs=(
        "${PYENV_ROOT}"
        "${PYENV_ROOT}/plugins/pyenv-virtualenv"
        # our bin repos have "postactivate"
        "${PYENV_ROOT}/versions/py-default/bin"
        "${PYENV_ROOT}/versions/pypy/bin"
    )
else
    # windows
    declare -ar dirs=(
        "${PYENV_ROOT}"
        "${PYENV_ROOT}/plugins/pyenv-virtualenv"
        # our bin repos have "postactivate"
        "${PYENV_ROOT}/versions/py-default-32/bin"
        "${PYENV_ROOT}/versions/py-default-64/bin"
    )
fi

for dir in ${dirs[@]} ; do
    do_git "${dir}"
done
